interface ICodeList {
  country: string;
  code: string;
}

export const countryList: ICodeList[] = [
  { country: "Cyprus", code: "+357" },
  { country: "Armenia", code: "+374" },
  { country: "Malaysia", code: "+60" },
  { country: "Indonesia", code: "+62" },
  { country: "Philippines", code: "+63" },
  { country: "Singapore", code: "+65" },
  { country: "Thailand", code: "+66" },
  { country: "Timor-Leste (East Timor)", code: "+670" },
  { country: "Brunei", code: "+673" },
  { country: "Kazakhstan", code: "+7" },
  { country: "Japan", code: "+81" },
  { country: "South Korea", code: "+82" },
  { country: "Vietnam", code: "+84" },
  { country: "North Korea", code: "+850" },
  { country: "Cambodia", code: "+855" },
  { country: "Laos", code: "+856" },
  { country: "China", code: "+86" },
  { country: "Bangladesh", code: "+880" },
  { country: "Turkey", code: "+90" },
  { country: "India", code: "+91" },
  { country: "Pakistan", code: "+92" },
  { country: "Afghanistan", code: "+93" },
  { country: "Sri Lanka", code: "+94" },
  { country: "Myanmar (Burma)", code: "+95" },
  { country: "Maldives", code: "+960" },
  { country: "Lebanon", code: "+961" },
  { country: "Jordan", code: "+962" },
  { country: "Syria", code: "+963" },
  { country: "Iraq", code: "+964" },
  { country: "Kuwait", code: "+965" },
  { country: "Saudi Arabia", code: "+966" },
  { country: "Yemen", code: "+967" },
  { country: "Oman", code: "+968" },
  { country: "Palestine", code: "+970" },
  { country: "United Arab Emirates", code: "+971" },
  { country: "Israel", code: "+972" },
  { country: "Bahrain", code: "+973" },
  { country: "Qatar", code: "+974" },
  { country: "Bhutan", code: "+975" },
  { country: "Mongolia", code: "+976" },
  { country: "Nepal", code: "+977" },
  { country: "Iran", code: "+98" },
  { country: "Tajikistan", code: "+992" },
  { country: "Turkmenistan", code: "+993" },
  { country: "Azerbaijan", code: "+994" },
  { country: "Georgia", code: "+995" },
  { country: "Kyrgyzstan", code: "+996" },
  { country: "Uzbekistan", code: "+998" },
];
